### Get info about the phonebook
GET http://localhost:3001/info

### Get all persons
GET http://localhost:3001/api/persons

### Get a person by ID
GET http://localhost:3001/api/persons/690928344e72c6b226be527b

### Get a person by non-existing ID
GET http://localhost:3001/api/persons/123456789012345678901234

### Get a person by malformatted ID
GET http://localhost:3001/api/persons/12345


### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Mattinen",
  "number": "123456"
}

### Add a person with missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123456"
}

### Add a person with missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Mattinen"
}

### Delete a person by ID
DELETE http://localhost:3001/api/persons/690a41eac61827f332454527