### Get info about the phonebook
GET http://localhost:3001/info

### Get all persons
GET http://localhost:3001/api/persons

### Get a person by ID
GET http://localhost:3001/api/persons/690928344e72c6b226be527b

### Delete a person by ID
DELETE http://localhost:3001/api/persons/1

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Mattinen",
  "number": "123456"
}

### Add a person with missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123456"
}

### Add a person with missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Mattinen"
}
